### ISSUE TITLE
进入直接OOM了

### ISSUE THREAD

**Issue by drkingwater** [darryrzhong/Android-MvvmComponent-App#18]
Process: com.mvvm.mvvmcomponent, PID: 31392
    java.lang.OutOfMemoryError: Failed to allocate a 24037772 byte allocation with 16777216 free bytes and 19MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2650)
        at android.content.res.Resources.loadDrawable(Resources.java:2555)
        at android.content.res.Resources.getDrawable(Resources.java:814)
        at android.content.res.XResources.getDrawable(XResources.java:790)
        at android.content.Context.getDrawable(Context.java:458)
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:455)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
        at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:86)
        at androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:94)
        at com.drz.main.viewholder.CustomPageViewHolder.onBind(CustomPageViewHolder.java:32)
        at com.drz.main.viewholder.CustomPageViewHolder.onBind(CustomPageViewHolder.java:20)
        at com.zhpan.bannerview.adapter.BannerPagerAdapter.createView(BannerPagerAdapter.java:92)
        at com.zhpan.bannerview.adapter.BannerPagerAdapter.getView(BannerPagerAdapter.java:84)
        at com.zhpan.bannerview.adapter.BannerPagerAdapter.instantiateItem(BannerPagerAdapter.java:56)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1224)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)

**Comment by du222** [comment]
够拉
